name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build:

    runs-on: ${{ matrix.os-name }}
    
    strategy:
      fail-fast: false
      matrix:
        os-name: [ubuntu-latest, windows-latest]


    steps:
      - name: Support longpaths on Windows
        if: "startsWith(matrix.os-name, 'windows')"
        run: git config --global core.longpaths true

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install cl.exe
        if: startsWith(matrix.os-name, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
      - uses: microsoft/setup-msbuild@v1
        if: startsWith(matrix.os-name, 'windows')
      - name: Setup GraalVM
        id: setup-graalvm
        uses: graalvm/setup-graalvm@v1
        if: startsWith(matrix.os-name, 'windows')
        with:
          version: 'mandrel-latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-repo-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Build with Maven
        run: ./mvnw -B formatter:validate verify --file pom.xml -Dnative
