name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build:

    runs-on: ${{ matrix.os-name }}
    
    strategy:
      fail-fast: false
      matrix:
        os-name: [ubuntu-latest, windows-latest]

    steps:
      - name: Support longpaths on Windows
        if: "startsWith(matrix.os-name, 'windows')"
        run: git config --global core.longpaths true

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Install cl.exe
        if: startsWith(matrix.os-name, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
      - uses: microsoft/setup-msbuild@v1
        if: startsWith(matrix.os-name, 'windows')
      - name: Setup GraalVM
        id: setup-graalvm
        uses: graalvm/setup-graalvm@v1
        if: startsWith(matrix.os-name, 'windows')
        with:
          version: 'mandrel-latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check format
        if: startsWith(matrix.os-name, 'ubuntu')
        run: ./mvnw -B formatter:validate --file pom.xml

      - name: Build with Maven
        run: ./mvnw -B verify --file pom.xml -Dnative
